import type { ProfileManager } from "../../config/profiles.ts";
import type { LazyConnectorMesh } from "../../connectors/lazy-mesh/index.ts";
import type { AutoUpdateRuntimeBag } from "../../extensions/auto-update-init.ts";
import type { PublisherKeyFetcher } from "../../extensions/registry-client.ts";
import type { LocalIndex } from "../../index/local-index.ts";
import type { LlmRegistry } from "../../llm/registry.ts";
import type { SessionMemoryStore } from "../../memory/session-memory-store.ts";
import type { SandboxRunner } from "../../platform/sandbox/sandbox-runner.ts";
import type { SyncScheduler } from "../../sync/scheduler.ts";
import type { Updater } from "../../updater/updater.ts";
import type { NimbusVault } from "../../vault/nimbus-vault.ts";
import type { VoiceService } from "../../voice/service.ts";
import type { AgentInvokeHandler } from "../agent-invoke.ts";
import type { PairingWindow } from "../lan-pairing.ts";
import type { LanServer } from "../lan-server.ts";
import type { ClientSession } from "../session.ts";
import type { WorkflowRunHandler } from "../workflow-invoke.ts";

export type BunSessionData = { session: ClientSession };

export type CreateIpcServerOptions = {
  listenPath: string;
  vault: NimbusVault;
  version: string;
  localIndex?: LocalIndex;
  extensionsDir?: string;
  openUrl?: (url: string) => Promise<void>;
  syncScheduler?: SyncScheduler;
  connectorMesh?: LazyConnectorMesh;
  getEmbeddingStatus?: () => Record<string, unknown>;
  startedAtMs?: number;
  agentInvoke?: AgentInvokeHandler;
  workflowRun?: WorkflowRunHandler;
  sessionMemoryStore?: SessionMemoryStore;
  dataDir?: string;
  configDir?: string;
  onClientConnected?: (clientId: string) => void;
  llmRegistry?: LlmRegistry;
  voiceService?: VoiceService;
  updater?: Updater;
  lanServer?: LanServer;
  lanPairingWindow?: PairingWindow;
  profileManager?: ProfileManager;
  sandboxRunner?: SandboxRunner;
  extensionsPublisherKeyFetcher?: PublisherKeyFetcher;
  extensionsEnforceAirGap?: boolean;
  extensionsAutoUpdate?: AutoUpdateRuntimeBag;
  extensionsAutoUpdateDiag?: {
    cachedUpdatesCount: () => number;
    intervalHours: number;
    airGapBlocked: boolean;
  };
};
