import { posix } from "node:path";

export interface NfpmInputs {
  /** Semver without a leading "v". */
  version: string;
  /** Directory holding the staged `nimbus`, `nimbus-gateway` (+ optional `nimbus-sandbox-helper`). */
  binDir: string;
  /** Directory holding the generated `/usr/local/bin` wrapper scripts (`nimbus`, `nimbus-gateway`). */
  wrapperDir: string;
  hasSandboxHelper: boolean;
}

/**
 * Render an nfpm v2 config that packages the Nimbus headless bundle as an `.rpm`
 * (and could emit a `.deb` from the same config). Mirrors the bespoke `.deb`
 * layout in package-linux-installers.ts: real binaries under /usr/lib/nimbus/bin,
 * thin wrappers in /usr/local/bin, bubblewrap + setcap helper.
 *
 * Pure: paths are interpolated, no filesystem access. The caller writes the YAML
 * and invokes `nfpm package`.
 */
export function renderNfpmConfig(i: NfpmInputs): string {
  const contents: string[] = [
    `  - src: ${posix.join(i.binDir, "nimbus-gateway")}`,
    `    dst: /usr/lib/nimbus/bin/nimbus-gateway`,
    `    file_info:\n      mode: 0755`,
    `  - src: ${posix.join(i.binDir, "nimbus")}`,
    `    dst: /usr/lib/nimbus/bin/nimbus`,
    `    file_info:\n      mode: 0755`,
    `  - src: ${posix.join(i.wrapperDir, "nimbus")}`,
    `    dst: /usr/local/bin/nimbus`,
    `    file_info:\n      mode: 0755`,
    `  - src: ${posix.join(i.wrapperDir, "nimbus-gateway")}`,
    `    dst: /usr/local/bin/nimbus-gateway`,
    `    file_info:\n      mode: 0755`,
  ];
  if (i.hasSandboxHelper) {
    contents.push(
      `  - src: ${posix.join(i.binDir, "nimbus-sandbox-helper")}`,
      `    dst: /usr/lib/nimbus/bin/nimbus-sandbox-helper`,
      `    file_info:\n      mode: 0755`,
    );
  }

  const scriptsBlock = i.hasSandboxHelper
    ? `scripts:\n  postinstall: ${posix.join(i.wrapperDir, "rpm-postinstall.sh")}\n`
    : "";

  return `# Generated by scripts/release/nfpm-config.ts — do not edit by hand.
name: nimbus-headless
arch: amd64
version: ${i.version}
maintainer: Nimbus Contributors <https://github.com/nimbus-agent/Nimbus>
description: Nimbus CLI and headless Gateway (local-first agent framework)
homepage: https://github.com/nimbus-agent/Nimbus
license: AGPL-3.0-only
section: utils
priority: optional
overrides:
  rpm:
    depends:
      - bubblewrap
      - libcap
  deb:
    depends:
      - bubblewrap
      - libcap2-bin
${scriptsBlock}contents:
${contents.join("\n")}
`;
}
