#!/usr/bin/env bun
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Parse a GNU coreutils `SHA256SUMS` file (`<hex-hash>  <filename>`, sorted by
 * filename) into a filename→hash map. Tolerates one or more spaces between the
 * hash and the filename and ignores blank lines.
 */
export function parseSha256Sums(text: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const rawLine of text.split("\n")) {
    const line = rawLine.trim();
    if (line === "") continue;
    const m = /^([0-9a-fA-F]{64})\s+\*?(.+)$/.exec(line);
    const hash = m?.[1];
    const filename = m?.[2];
    if (hash === undefined || filename === undefined) continue;
    map.set(filename.trim(), hash.toLowerCase());
  }
  return map;
}

export interface ManifestAssets {
  macArm64Sha256: string;
  macX64Sha256: string;
  linuxX64Sha256: string;
  winX64Sha256: string;
}

export interface ManifestInputs {
  /** Semver without a leading "v". */
  version: string;
  /** "owner/repo", e.g. "nimbus-agent/Nimbus". */
  repo: string;
  assets: ManifestAssets;
}

const DESC = "Local-first AI agent framework (headless gateway + CLI)";
const LICENSE = "AGPL-3.0-only";

function releaseUrl(repo: string, version: string, file: string): string {
  return `https://github.com/${repo}/releases/download/v${version}/${file}`;
}

export function renderHomebrewFormula(i: ManifestInputs): string {
  const { version, repo, assets } = i;
  const homepage = `https://github.com/${repo}`;
  const macArm = releaseUrl(repo, version, "nimbus-headless-macos-arm64.tar.gz");
  const macX64 = releaseUrl(repo, version, "nimbus-headless-macos-x64.tar.gz");
  const linuxX64 = releaseUrl(repo, version, `nimbus-headless-linux-amd64-v${version}.tar.gz`);
  return `# typed: false
# frozen_string_literal: true

# Homebrew formula for Nimbus (headless gateway + CLI).
# Generated by scripts/release/package-manager-manifests.ts — do not edit by hand.
class Nimbus < Formula
  desc "${DESC}"
  homepage "${homepage}"
  version "${version}"
  license "${LICENSE}"

  on_macos do
    on_arm do
      url "${macArm}"
      sha256 "${assets.macArm64Sha256}"
    end
    on_intel do
      url "${macX64}"
      sha256 "${assets.macX64Sha256}"
    end
  end

  on_linux do
    on_intel do
      url "${linuxX64}"
      sha256 "${assets.linuxX64Sha256}"
    end
  end

  def install
    bin.install "nimbus"
    bin.install "nimbus-gateway"
  end

  test do
    assert_match "${version}", shell_output("#{bin}/nimbus --version")
  end
end
`;
}

export function renderScoopManifest(i: ManifestInputs): string {
  const { version, repo, assets } = i;
  const winUrl = releaseUrl(repo, version, "nimbus-headless-windows-x64.zip");
  const manifest = {
    version,
    description: DESC,
    homepage: `https://github.com/${repo}`,
    license: LICENSE,
    architecture: {
      "64bit": { url: winUrl, hash: assets.winX64Sha256 },
    },
    bin: ["nimbus.exe", "nimbus-gateway.exe"],
    checkver: { github: `https://github.com/${repo}` },
    autoupdate: {
      architecture: {
        "64bit": {
          url: `https://github.com/${repo}/releases/download/v$version/nimbus-headless-windows-x64.zip`,
        },
      },
    },
  };
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

export interface BuildOptions {
  version: string;
  repo: string;
  sha256SumsPath: string;
  outDir: string;
}

export interface BuildResult {
  formulaPath: string;
  scoopPath: string;
}

function requireHash(map: Map<string, string>, file: string): string {
  const h = map.get(file);
  if (!h) {
    throw new Error(
      `package-manager-manifests: required release asset not found in SHA256SUMS: ${file}`,
    );
  }
  return h;
}

export function buildManifestsToDir(opts: BuildOptions): BuildResult {
  const version = opts.version.replace(/^v/, "");
  const sums = parseSha256Sums(readFileSync(opts.sha256SumsPath, "utf8"));
  const inputs: ManifestInputs = {
    version,
    repo: opts.repo,
    assets: {
      macArm64Sha256: requireHash(sums, "nimbus-headless-macos-arm64.tar.gz"),
      macX64Sha256: requireHash(sums, "nimbus-headless-macos-x64.tar.gz"),
      linuxX64Sha256: requireHash(sums, `nimbus-headless-linux-amd64-v${version}.tar.gz`),
      winX64Sha256: requireHash(sums, "nimbus-headless-windows-x64.zip"),
    },
  };
  mkdirSync(opts.outDir, { recursive: true });
  const formulaPath = join(opts.outDir, "nimbus.rb");
  const scoopPath = join(opts.outDir, "nimbus.json");
  writeFileSync(formulaPath, renderHomebrewFormula(inputs), "utf8");
  writeFileSync(scoopPath, renderScoopManifest(inputs), "utf8");
  return { formulaPath, scoopPath };
}

function parseArg(flag: string): string | undefined {
  const idx = process.argv.indexOf(flag);
  return idx >= 0 ? process.argv[idx + 1] : undefined;
}

if (import.meta.main) {
  const version = parseArg("--version") ?? process.env["NIMBUS_RELEASE_VERSION"];
  const repo = parseArg("--repo") ?? "nimbus-agent/Nimbus";
  const sha256SumsPath = parseArg("--sha256sums");
  const outDir = parseArg("--out-dir") ?? ".";
  if (!version || !sha256SumsPath) {
    console.error(
      "Usage: bun scripts/release/package-manager-manifests.ts --version <v> --sha256sums <path> [--repo owner/repo] [--out-dir dir]",
    );
    process.exit(1);
  }
  const res = buildManifestsToDir({ version, repo, sha256SumsPath, outDir });
  console.log(`wrote ${res.formulaPath}`);
  console.log(`wrote ${res.scoopPath}`);
}
