import { ensureVaultEd25519Keypair } from "../util/ed25519.ts";
import type { NimbusVault } from "../vault/nimbus-vault.ts";

/** Vault key for the share signing seed (base64, 32-byte Ed25519 seed). NEVER leaves the Vault. */
export const SHARE_SIGNING_PRIVKEY = "share.signing.privkey";
/** Vault key for the share signing public key (base64). Safe to surface — it's embedded in shares. */
export const SHARE_SIGNING_PUBKEY = "share.signing.pubkey";

/**
 * Resolve the share signing keypair from the Vault, generating + storing it on first use. The
 * private seed is Vault-only — it is read here solely to thread into the in-process signing call;
 * it is never returned over IPC/HTTP, persisted to a DB column, or logged.
 *
 * A stored pair that is absent, malformed or mismatched (a privkey from one keypair next to a
 * pubkey from another, which would sign shares verifiers reject) is regenerated by the shared
 * `ensureVaultEd25519Keypair` (`util/ed25519.ts`), which `toolgen/toolgen-keypair.ts` uses too.
 * The key names stay HERE: static rule D21 confines the `share.signing.privkey` literal to this
 * file.
 */
export function ensureShareKeypair(
  vault: NimbusVault,
): Promise<{ privkeyB64: string; pubkeyB64: string }> {
  return ensureVaultEd25519Keypair(vault, SHARE_SIGNING_PRIVKEY, SHARE_SIGNING_PUBKEY);
}
