import { describe, expect, test } from "bun:test";
import type { NimbusVault } from "../vault/nimbus-vault.ts";
import { sweepToolgenCredentials } from "./toolgen-credential-sweep.ts";
import { toolCredentialKey } from "./toolgen-credentials.ts";
import {
  ensureToolgenKeypair,
  TOOLGEN_SIGNING_PRIVKEY,
  TOOLGEN_SIGNING_PUBKEY,
} from "./toolgen-keypair.ts";

/** Minimal in-memory `NimbusVault` fake — no real Vault/OS keychain involved. */
class FakeVault implements NimbusVault {
  private readonly store = new Map<string, string>();

  async get(key: string): Promise<string | null> {
    return this.store.get(key) ?? null;
  }

  async set(key: string, value: string): Promise<void> {
    this.store.set(key, value);
  }

  async delete(key: string): Promise<void> {
    this.store.delete(key);
  }

  async listKeys(prefix?: string): Promise<string[]> {
    return [...this.store.keys()].filter((k) => !prefix || k.startsWith(prefix));
  }
}

describe("sweepToolgenCredentials", () => {
  test("sweeps every per-host credential", async () => {
    const vault = new FakeVault();
    await vault.set(toolCredentialKey("t1", "api.example.com"), '{"type":"bearer","token":"x"}');
    await vault.set(toolCredentialKey("t2", "other.example.com"), '{"type":"bearer","token":"y"}');
    expect(await sweepToolgenCredentials(vault)).toBe(2);
    expect(await vault.get(toolCredentialKey("t1", "api.example.com"))).toBeNull();
    expect(await vault.get(toolCredentialKey("t2", "other.example.com"))).toBeNull();
  });

  test("RETAINS the signing keypair — sweeping it would orphan every saved tool", async () => {
    const vault = new FakeVault();
    await ensureToolgenKeypair(vault);
    await vault.set(toolCredentialKey("t1", "api.example.com"), "{}");
    // Proves RETENTION, not just that the per-host key is gone: capture the exact values first —
    // a version of the sweep that deleted and silently regenerated the keypair would still pass a
    // weaker "not null" check. `ensureToolgenKeypair` regenerates on a missing/corrupt Vault, so a
    // sweep that (wrongly) deleted these two keys would leave `get()` returning null right after,
    // which the two `not.toBeNull()` assertions below catch either way -- but pinning the exact
    // base64 values additionally rules out "deleted, then silently regenerated by something else".
    const privBefore = await vault.get(TOOLGEN_SIGNING_PRIVKEY);
    const pubBefore = await vault.get(TOOLGEN_SIGNING_PUBKEY);
    expect(privBefore).not.toBeNull();
    expect(pubBefore).not.toBeNull();

    await sweepToolgenCredentials(vault);

    expect(await vault.get(TOOLGEN_SIGNING_PRIVKEY)).toBe(privBefore);
    expect(await vault.get(TOOLGEN_SIGNING_PUBKEY)).toBe(pubBefore);
  });

  test("leaves non-toolgen keys untouched", async () => {
    const vault = new FakeVault();
    await vault.set("github.pat", "ghp_x");
    await sweepToolgenCredentials(vault);
    expect(await vault.get("github.pat")).toBe("ghp_x");
  });

  test("sweeps a crash-orphaned key for a tool that no longer exists anywhere", async () => {
    const vault = new FakeVault();
    await vault.set(toolCredentialKey("gone", "api.example.com"), "{}");
    expect(await sweepToolgenCredentials(vault)).toBe(1);
    expect(await vault.get(toolCredentialKey("gone", "api.example.com"))).toBeNull();
  });

  test("an empty Vault sweeps zero and does not throw", async () => {
    const vault = new FakeVault();
    expect(await sweepToolgenCredentials(vault)).toBe(0);
  });

  test("is idempotent — a second sweep over an already-clean Vault also returns zero", async () => {
    const vault = new FakeVault();
    await vault.set(toolCredentialKey("t1", "api.example.com"), "{}");
    await sweepToolgenCredentials(vault);
    expect(await sweepToolgenCredentials(vault)).toBe(0);
  });
});
