/**
 * The only sanctioned source of a `new Worker()` path in the gateway.
 *
 * Each import embeds a pre-bundled worker into the compiled binary and yields a path the Worker
 * realm can actually load — inside a compiled binary that is a `B:/~BUN/root/...` virtual-FS path,
 * and when running from source it is the real file on disk. One code path for both, so a test
 * exercises what the binary ships. That is the specific thing F15 and F22 got wrong: every
 * source-tree test passed while both workers were dead in every packaged build.
 *
 * The imported files are BUILD OUTPUT, generated by `bun run build:workers` from
 * `worker-entries.ts` and gitignored. They are present after any `bun install`, because `prepare`
 * builds them, and `compile-gateway.ts` rebuilds them immediately before `bun build --compile` —
 * the same guarantee, and the same fail-loud handling, that `packages/admin-console/dist` already
 * has in `ipc/embedded-assets.ts`.
 *
 * If one of these imports fails to resolve, run `bun run build:workers`. Do NOT "fix" it by
 * reverting a spawn site to `new URL("./worker.ts", import.meta.url)`: that form works in dev and
 * silently ships a dead worker.
 */
import embeddingWorkerJs from "../../dist/workers/embedding-worker.js" with { type: "file" };
import queryGuardWorkerJs from "../../dist/workers/query-guard-worker.js" with { type: "file" };

/** Entry path for `embedding/worker-bridge.ts`. */
export const EMBEDDING_WORKER_PATH: string = embeddingWorkerJs;

/** Entry path for `db/query-guard.ts`. */
export const QUERY_GUARD_WORKER_PATH: string = queryGuardWorkerJs;
