#!/usr/bin/env bash
# Which read path does the macOS sandbox profile still need?
#
# Run this on ANY Mac from a checkout of this repo. It takes about ten seconds and needs nothing
# but bun — no `bun install`, since the profile generator it imports has no external dependencies.
#
#   bash scripts/diagnostics/macos-sandbox-bisect.sh
#
# Why it exists: `sandbox-exec` is a macOS kernel feature, so the profile cannot be exercised on
# Windows or Linux, in Docker, or in CI any faster than one push per question. Three kernel-side
# ways of asking WHAT was denied have already failed on macos-15 — a plain `(deny default)` logs
# nothing, `(trace "<file>")` writes no file on modern macOS, and `(deny default (with report))` is
# rejected at compile time ("report modifier does not apply to deny action"). So this asks the
# profile what it is missing instead: same profile, one extra rule at a time, report which flip it.
#
# CI has narrowed it this far already:
#   round 1 — only `(allow file-read* (subpath "/"))` fixes it; write/ioctl/mach/shm/sysctl/
#             process/system all change nothing. It is a file READ.
#   round 2 — none of cwd-parent, temp root, HOME, /dev, /private/var, /usr, /Library, /opt fix it.
# So the needed path is something `(subpath "/")` covers and none of those do.
set -uo pipefail

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "This only runs on macOS — sandbox-exec is a macOS kernel feature." >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
DARWIN_TS="$REPO_ROOT/packages/gateway/src/platform/sandbox/darwin.ts"
[[ -f "$DARWIN_TS" ]] || { echo "not a Nimbus checkout: $DARWIN_TS missing" >&2; exit 1; }

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/work" "$WORK/sbx"
CWD="$(cd "$WORK/work" && pwd -P)"          # -P: /var is a symlink to /private/var
# The runner hands the child a PRIVATE scratch directory and redirects TMPDIR/TMP/TEMP at it
# (`createDarwinSandboxRunner`), rather than letting it fall back to the per-user
# `/private/var/folders/<hash>/<hash>/T` the profile deliberately does not grant. Pointing this
# probe's baseline at the cwd instead would be a different temp-directory model from the one that
# ships, which is exactly the drift that makes a `FIXES IT` line untrustworthy.
SBX="$(cd "$WORK/sbx" && pwd -P)"
BUN="$(command -v bun)"
[[ -n "$BUN" ]] || { echo "bun not on PATH" >&2; exit 1; }
BUN_BIN="$(cd "$(dirname "$BUN")" && pwd -P)"
BUN_HOME="$(dirname "$BUN_BIN")"
printf 'process.stdout.write("ok")' > "$CWD/hello.js"

# The baseline is GENERATED by the shipping implementation, never transcribed from it.
#
# This file used to carry its own copy of the profile with a "keep these in sync by hand" note,
# and it drifted within the same branch: the copy was written before `/private/var/{db,select,run}`
# widened past `db/dyld`, before the derived per-user cache directory was granted, and before the
# ancestor chain was emitted as literals. A baseline NARROWER than what ships is the one failure
# mode a bisect cannot survive — every probe is measured against it, so a rule the real profile
# already grants shows up as `FIXES IT`, and the reported "fix" is a widening nobody needs.
cat > "$WORK/print-profile.ts" <<'TS'
const [, , mod, cwd, tmp, ...read] = process.argv;
const { generateSbplProfile } = await import(mod!);
process.stdout.write(
  generateSbplProfile({
    cwd: cwd!,
    tmpdir: tmp!,
    // The probe declares no network and no extra writes: it runs one `hello.js` that writes to
    // stdout. `read` carries only what makes `bun` itself resolvable, which on a real extension
    // would be the manifest's own `permissions.filesystem.read`.
    policy: {
      id: "macos-sandbox-bisect",
      permissions: { network: [], filesystem: { read, write: [] } },
    },
  }),
);
TS

BASE="$WORK/base.sb"
if ! "$BUN" run "$WORK/print-profile.ts" "$DARWIN_TS" "$CWD" "$SBX" "$BUN_BIN" "$BUN_HOME" > "$BASE"; then
  echo "could not generate the profile from $DARWIN_TS" >&2
  exit 1
fi
[[ -s "$BASE" ]] || { echo "generated profile is empty" >&2; exit 1; }

try() {
  local label="$1" rule="$2" prof="$WORK/p.sb"
  { cat "$BASE"; printf '\n'; [[ -n "$rule" ]] && printf '%s\n' "$rule"; } > "$prof"
  local out status
  out="$(cd "$CWD" && TMPDIR="$SBX" TMP="$SBX" TEMP="$SBX" \
    /usr/bin/sandbox-exec -f "$prof" "$BUN" "$CWD/hello.js" 2>&1)"
  status=$?
  if [[ $status -eq 0 && "$out" == "ok" ]]; then
    printf '  FIXES IT   %-46s %s\n' "$label" "$rule"
  else
    printf '  no change  %-46s (exit %s)\n' "$label" "$status"
  fi
}

echo "baseline — the profile exactly as it ships:"
try "(no extra rule)" ""
echo
echo "sanity — the diagnostic that CI says works:"
try "read anywhere" '(allow file-read* (subpath "/"))'
echo
# Single-quoted on purpose: in double quotes bash reads the backticks below as command
# substitution, runs `subpath "/"` in a subshell, and prints the line with the phrase MISSING
# plus a "subpath: command not found" on stderr.
echo 'candidates `(subpath "/")` covers that round 2 did not test:'
try "/private (all of it)"        '(allow file-read* (subpath "/private"))'
try "/private/tmp"                '(allow file-read* (subpath "/private/tmp"))'
try "/sbin"                       '(allow file-read* (subpath "/sbin"))'
try "/Applications"               '(allow file-read* (subpath "/Applications"))'
try "/Volumes"                    '(allow file-read* (subpath "/Volumes"))'
try "/System/Volumes/Data"        '(allow file-read* (subpath "/System/Volumes/Data"))'
try "/cores"                      '(allow file-read* (subpath "/cores"))'
try "the root directory itself"   '(allow file-read* (literal "/"))'
try "/Users (all users)"          '(allow file-read* (subpath "/Users"))'
echo
echo "Report the FIXES IT line. The fix is the narrowest rule that flips it —"
echo 'never (subpath "/"), which is only the diagnostic.'
