#!/usr/bin/env bun
import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dir, "..");
const CONNECTORS_DIR = join(REPO_ROOT, "packages", "mcp-connectors");
const OUT = join(
  REPO_ROOT,
  "packages",
  "gateway",
  "src",
  "connectors",
  "bundled-connector-registry.ts",
);

export function bundledConnectorIds(dir: string = CONNECTORS_DIR): string[] {
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(join(dir, e.name, "src", "server.ts")))
    .map((e) => e.name)
    .sort((a, b) => a.localeCompare(b));
}

function render(ids: readonly string[]): string {
  const entries = ids
    .map(
      (id) =>
        `  ${JSON.stringify(id)}: () => import("../../../mcp-connectors/${id}/src/server.ts"),`,
    )
    .join("\n");
  return `// GENERATED by scripts/gen-bundled-connector-registry.ts — do not edit by hand.
// Re-run: bun run gen:connector-registry
//
// Every first-party connector entrypoint, as a lazy dynamic import. The imports are static enough
// for the bundler to retain all ${ids.length} in the compiled gateway binary, and lazy enough that
// only the requested connector is ever evaluated.

export const BUNDLED_CONNECTORS: Readonly<Record<string, () => Promise<unknown>>> = {
${entries}
};
`;
}

if (import.meta.main) {
  const ids = bundledConnectorIds();
  writeFileSync(OUT, render(ids));
  // Biome's FORMATTER strips unnecessary quotes from object keys, and it is the authority on which
  // ids need them (`"monte-carlo"` does, `airflow` does not). Formatting the output here keeps the
  // generated file canonical by construction rather than duplicating that policy in `render()`,
  // which would silently rot the next time the formatter's rules change. Without this the file
  // fails `bun run lint`.
  const fmt = Bun.spawnSync(["bunx", "biome", "check", "--write", OUT], {
    stdout: "inherit",
    stderr: "inherit",
  });
  if (fmt.exitCode !== 0) {
    console.error("gen-bundled-connector-registry: biome failed to format the generated file");
    process.exit(1);
  }
  console.log(`wrote ${OUT} with ${ids.length} connectors`);
}
