#!/usr/bin/env bun
import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dir, "..");
const CONNECTORS_DIR = join(REPO_ROOT, "packages", "mcp-connectors");
const OUT = join(
  REPO_ROOT,
  "packages",
  "gateway",
  "src",
  "connectors",
  "bundled-connector-registry.ts",
);

export function bundledConnectorIds(dir: string = CONNECTORS_DIR): string[] {
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(join(dir, e.name, "src", "server.ts")))
    .map((e) => e.name)
    .sort((a, b) => a.localeCompare(b));
}

/**
 * Where a connector entrypoint is imported FROM.
 *
 * `workspace` (the default) emits a relative path into `packages/mcp-connectors`, which is where
 * the connectors live today. `package` emits a bare specifier into `@nimbus-dev/connectors`, which
 * is where they live after the extraction.
 *
 * The flag exists so the extraction's central assumption — that `bun build --compile` embeds a
 * BARE-specifier dynamic import as reliably as a relative one — can be proven by
 * `test:connector-boot` before a single file moves. If that proof fails, the design is wrong and
 * nothing should be moved; a flag is cheap and an unwound migration is not.
 */
function specifierFor(id: string): string {
  return process.env["NIMBUS_CONNECTOR_SPECIFIER"] === "package"
    ? `@nimbus-dev/connectors/${id}`
    : `../../../mcp-connectors/${id}/src/server.ts`;
}

function render(ids: readonly string[]): string {
  const entries = ids
    .map((id) => `  ${JSON.stringify(id)}: () => import("${specifierFor(id)}"),`)
    .join("\n");
  return `// GENERATED by scripts/gen-bundled-connector-registry.ts — do not edit by hand.
// Re-run: bun run gen:connector-registry
//
// Every first-party connector entrypoint, as a lazy dynamic import. The imports are static enough
// for the bundler to retain all ${ids.length} in the compiled gateway binary, and lazy enough that
// only the requested connector is ever evaluated.

export const BUNDLED_CONNECTORS: Readonly<Record<string, () => Promise<unknown>>> = {
${entries}
};
`;
}

if (import.meta.main) {
  const ids = bundledConnectorIds();
  writeFileSync(OUT, render(ids));
  // Biome's FORMATTER strips unnecessary quotes from object keys, and it is the authority on which
  // ids need them (`"monte-carlo"` does, `airflow` does not). Formatting the output here keeps the
  // generated file canonical by construction rather than duplicating that policy in `render()`,
  // which would silently rot the next time the formatter's rules change. Without this the file
  // fails `bun run lint`.
  const fmt = Bun.spawnSync(["bunx", "biome", "check", "--write", OUT], {
    stdout: "inherit",
    stderr: "inherit",
  });
  if (fmt.exitCode !== 0) {
    console.error("gen-bundled-connector-registry: biome failed to format the generated file");
    process.exit(1);
  }
  console.log(`wrote ${OUT} with ${ids.length} connectors`);
}
