#!/usr/bin/env bun
import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dir, "..");
const CONNECTORS_DIR = join(REPO_ROOT, "packages", "mcp-connectors");
const OUT = join(
  REPO_ROOT,
  "packages",
  "gateway",
  "src",
  "connectors",
  "bundled-connector-registry.ts",
);

export function bundledConnectorIds(dir: string = CONNECTORS_DIR): string[] {
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(join(dir, e.name, "src", "server.ts")))
    .map((e) => e.name)
    .sort((a, b) => a.localeCompare(b));
}

/**
 * Where a connector entrypoint is imported FROM.
 *
 * `package` (the DEFAULT) emits a bare specifier into `@nimbus-dev/connectors`, the published
 * package the connectors now live in. `workspace` emits a relative path into
 * `packages/mcp-connectors`, the in-repo copy that has not been deleted yet.
 *
 * The default flipped once the assumption the flag existed to test was proven: that
 * `bun build --compile` embeds a BARE-specifier dynamic import as reliably as a relative one.
 * Measured against the published 0.1.1 tarball, a compiled binary booted all 94 connectors with
 * the same verdict as the relative build — 89 answered, 5 refused without credentials, 0 failed.
 *
 * `workspace` is kept, not as a fallback but as a bisection tool: if a connector misbehaves after
 * the switch, regenerating against the in-repo copy says whether the package boundary is implicated
 * or the connector itself is. It stops being meaningful once packages/mcp-connectors is deleted.
 */
function specifierFor(id: string): string {
  return process.env["NIMBUS_CONNECTOR_SPECIFIER"] === "workspace"
    ? `../../../mcp-connectors/${id}/src/server.ts`
    : `@nimbus-dev/connectors/${id}`;
}

function render(ids: readonly string[]): string {
  const entries = ids
    .map((id) => `  ${JSON.stringify(id)}: () => import("${specifierFor(id)}"),`)
    .join("\n");
  return `// GENERATED by scripts/gen-bundled-connector-registry.ts — do not edit by hand.
// Re-run: bun run gen:connector-registry
//
// Every first-party connector entrypoint, as a lazy dynamic import. The imports are static enough
// for the bundler to retain all ${ids.length} in the compiled gateway binary, and lazy enough that
// only the requested connector is ever evaluated.

export const BUNDLED_CONNECTORS: Readonly<Record<string, () => Promise<unknown>>> = {
${entries}
};
`;
}

if (import.meta.main) {
  const ids = bundledConnectorIds();
  writeFileSync(OUT, render(ids));
  // Biome's FORMATTER strips unnecessary quotes from object keys, and it is the authority on which
  // ids need them (`"monte-carlo"` does, `airflow` does not). Formatting the output here keeps the
  // generated file canonical by construction rather than duplicating that policy in `render()`,
  // which would silently rot the next time the formatter's rules change. Without this the file
  // fails `bun run lint`.
  const fmt = Bun.spawnSync(["bunx", "biome", "check", "--write", OUT], {
    stdout: "inherit",
    stderr: "inherit",
  });
  if (fmt.exitCode !== 0) {
    console.error("gen-bundled-connector-registry: biome failed to format the generated file");
    process.exit(1);
  }
  console.log(`wrote ${OUT} with ${ids.length} connectors`);
}
