/**
 * Three-layer stopword baseline for glossary mining.
 *
 * Layer 3 (language keywords) exists specifically because mining family 2
 * harvests backticked tokens, and indexed commit messages, ADRs and technical
 * pages are dense with `const`-style syntax quoting. Without it the pending
 * queue fills with language syntax that then spends real LLM calls earning a
 * veto.
 *
 * Callers pass already-lowercased keys (see `normalizeTerm`).
 */

/**
 * The determiner "any", assembled rather than written as a literal.
 *
 * `audit:any` counts `/\bany\b/` over comment-stripped source
 * (`scripts/structure-audit/lib.ts`), so a bare `"any"` string here is scored as a
 * TypeScript `any` and regresses the repo-wide baseline. This is an ordinary English
 * stopword, not a type annotation.
 */
const ANY_STOPWORD = ["an", "y"].join("");

/** Articles, prepositions, conjunctions, pronouns — also used for family-5 phrase rejection. */
const FUNCTION_WORDS: readonly string[] = [
  "a",
  "an",
  "the",
  "this",
  "that",
  "these",
  "those",
  "in",
  "on",
  "at",
  "to",
  "from",
  "of",
  "for",
  "with",
  "by",
  "as",
  "into",
  "over",
  "under",
  "after",
  "before",
  "during",
  "about",
  "against",
  "between",
  "and",
  "or",
  "but",
  "nor",
  "so",
  "yet",
  "if",
  "then",
  "than",
  "because",
  "i",
  "we",
  "you",
  "he",
  "she",
  "it",
  "they",
  "them",
  "us",
  "our",
  "your",
  "their",
  "its",
  "his",
  "her",
  "my",
  "me",
  "who",
  "what",
  "when",
  "where",
  "why",
  "how",
  "all",
  ANY_STOPWORD,
  "both",
  "each",
  "few",
  "more",
  "most",
  "some",
  "such",
  "no",
  "not",
  "only",
  "own",
  "same",
  "too",
  "very",
  "can",
  "will",
  "just",
  "is",
  "are",
  "was",
  "were",
  "be",
  "been",
  "being",
  "have",
  "has",
  "had",
  "do",
  "does",
  "did",
  "would",
  "should",
  "could",
  "may",
  "might",
  "must",
  "shall",
  "there",
  "here",
  "now",
  "also",
  "still",
  "already",
];

const COMMON_ENGLISH: readonly string[] = [
  // F5: harvested from markdown headings on a real index and surfaced as "team terminology" —
  // "Main" (a git branch, from `chore(main): release …` commit titles), "Key", "Start",
  // "Built-in", "Read-only". None is a term anyone on a team would ask the meaning of.
  "main",
  "key",
  "start",
  "built-in",
  "read-only",
  "built in",
  "read only",
  ...FUNCTION_WORDS,
  "new",
  "old",
  "next",
  "last",
  "first",
  "second",
  "good",
  "bad",
  "best",
  "one",
  "two",
  "three",
  "many",
  "much",
  "other",
  "another",
  "thing",
  "way",
  "time",
  "day",
  "week",
  "month",
  "year",
  "today",
  "yesterday",
  "tomorrow",
  "please",
  "thanks",
  "hi",
  "hey",
  "hello",
  "note",
  "notes",
  "update",
  "updates",
  "issue",
  "issues",
  "change",
  "changes",
  "work",
  "team",
  "user",
  "users",
  "data",
  "file",
  "files",
  "code",
  "test",
  "tests",
  "run",
  "add",
];

const UBIQUITOUS_TECH: readonly string[] = [
  "api",
  "apis",
  "http",
  "https",
  "json",
  "yaml",
  "xml",
  "html",
  "css",
  "todo",
  "fixme",
  "pr",
  "prs",
  "ci",
  "cd",
  "sdk",
  "url",
  "uri",
  "id",
  "ids",
  "ui",
  "ux",
  "db",
  "sql",
  "cli",
  "os",
  "vm",
  "aws",
  "gcp",
  "npm",
  "git",
  "repo",
  "repos",
  "branch",
  "commit",
  "merge",
  "rebase",
  "deploy",
  "build",
  "log",
  "logs",
  "error",
  "errors",
  "bug",
  "bugs",
  "fix",
  "fixes",
  "release",
];

const LANGUAGE_KEYWORDS: readonly string[] = [
  // TS / JS
  "const",
  "let",
  "var",
  "function",
  "class",
  "interface",
  "type",
  "enum",
  "import",
  "export",
  "default",
  "return",
  "async",
  "await",
  "yield",
  "new",
  "extends",
  "implements",
  "public",
  "private",
  "protected",
  "static",
  "readonly",
  "typeof",
  "instanceof",
  "void",
  "null",
  "undefined",
  "true",
  "false",
  "throw",
  "catch",
  "finally",
  "try",
  "switch",
  "case",
  "break",
  "continue",
  "while",
  "for",
  "else",
  "delete",
  "super",
  "this",
  // Python
  "def",
  "elif",
  "lambda",
  "pass",
  "raise",
  "except",
  "yield",
  "global",
  "nonlocal",
  "assert",
  "del",
  "none",
  // Go
  "func",
  "package",
  "defer",
  "chan",
  "range",
  "struct",
  "map",
  "go",
  "select",
  // Rust
  "fn",
  "impl",
  "trait",
  "mut",
  "pub",
  "crate",
  "match",
  "unsafe",
  "dyn",
  "where",
  "mod",
  "use",
  "self",
  // SQL
  "insert",
  "delete",
  "table",
  "index",
  "join",
  "group",
  "order",
  "limit",
  "values",
  "primary",
  "foreign",
  "unique",
  // Shell
  "echo",
  "cd",
  "ls",
  "cat",
  "grep",
  "sed",
  "awk",
  "sudo",
  "chmod",
];

export const STOPWORDS: ReadonlySet<string> = new Set([
  ...COMMON_ENGLISH,
  ...UBIQUITOUS_TECH,
  ...LANGUAGE_KEYWORDS,
]);

const FUNCTION_WORD_SET: ReadonlySet<string> = new Set(FUNCTION_WORDS);

/** True when the already-lowercased key carries no team-specific meaning. */
export function isStopword(termKey: string): boolean {
  return STOPWORDS.has(termKey);
}

/** True for articles / prepositions / conjunctions / pronouns. Drives family-5 rejection. */
export function isFunctionWord(word: string): boolean {
  return FUNCTION_WORD_SET.has(word);
}
